spring.profiles.active: local

server.servlet.context-path: /api

---

spring:
  profiles: local

server:
  port: 8090

zuul:
  routes:
    msg-api:
      path: /messages/**
      url: http://localhost:8080/api/v1/messages

